In [1]:
import os
import pandas as pd
import numpy as np

In [3]:
test = pd.read_csv('data/test.csv')
preds = pd.read_csv('message_passing_nn/data/submission/all_types_new_features/submit/submit-00242500_model-larger.csv')

In [4]:
COUPLING_TYPE_STATS = [
    # type   #mean, std, min, max
    '1JHC',  94.9761528641869,   18.27722399839607,   66.6008,   204.8800,
    '2JHC',  -0.2706244378832,    4.52360876732858,  -36.2186,    42.8192,
    '3JHC',   3.6884695895355,    3.07090647005439,  -18.5821,    76.0437,
    '1JHN',  47.4798844844683,   10.92204561670947,   24.3222,    80.4187,
    '2JHN',   3.1247536134185,    3.67345877025737,   -2.6209,    17.7436,
    '3JHN',   0.9907298624944,    1.31538940138001,   -3.1724,    10.9712,
    '2JHH', -10.2866051639817,    3.97960190019757,  -35.1761,    11.8542,
    '3JHH',   4.7710233597359,    3.70498129755812,   -3.0205,    17.4841,
]
NUM_COUPLING_TYPE = len(COUPLING_TYPE_STATS)//5

COUPLING_TYPE_MEAN = [COUPLING_TYPE_STATS[i*5+1] for i in range(NUM_COUPLING_TYPE)]
COUPLING_TYPE_STD = [COUPLING_TYPE_STATS[i*5+2] for i in range(NUM_COUPLING_TYPE)]

In [5]:
predict = []
for i, row in test.iterrows():
    if i % 10000 == 0: print(i)
    #truth = row.scalar_coupling_constant
    pred = preds.loc[i].scalar_coupling_constant
    types_mean = COUPLING_TYPE_MEAN[COUPLING_TYPE_STATS.index(row.type)//5]
    types_std = COUPLING_TYPE_STD[COUPLING_TYPE_STATS.index(row.type)//5]
    predict.append(pred * types_std + types_mean)

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
1390000
1400000
1410000
1420000
1430000
1440000
1450000
1460000
1470000
1480000
1490000
1500000
1510000
1520000
1530000
1540000
1550000
1560000
1570000
1580000
1590000
1600000
1610000
1620000
1630000
1640000
1650000
1660000
1670000
1680000
1690000
1700000
1710000
1720000
1730000
1740000
1750000
1760000
1770000
1780000
1790000
1800000
1810000
1820000
1830000
1840000
1850000
1860000
1870000
1880000
1890000
1900000
1910000
1920000
1930000
1940000
1950000
1960000
1970000
1980000
1990000
2000000
2010000
2020000
2030000
2040000
2050000
2060000
2070000
2080000
2090000
2100000
2110000
2120000
2130000
2140000
2150000
2160000
2170000
2180000
2190000
2200000
2210000
2220000
2230000
2240000
2250000
2260000
2270000
2280000
2290000
2300000
2310000
2320000
2330000
2340000
2350000
2360000
2370000
2380000
2390000
2400000
2410000
2420000
2430000
2440000
2450000
2460000
2470000
2480000
2490000
2500000

In [6]:
predict_compare = pd.read_csv(('message_passing_nn/data/submission/all_types_yukawa_radius_set2set/'
                               'submit/set2set_highbs_mpnn_larger_single.csv'))

In [12]:
np.mean(predict)

15.884407671333248

In [8]:
np.mean(predict_compare.scalar_coupling_constant)

15.877525952360596

In [9]:
test['scalar_coupling_constant'] = predict

In [10]:
test.head()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
0,4658147,dsgdb9nsd_000004,2,0,2JHC,12.205259
1,4658148,dsgdb9nsd_000004,2,1,1JHC,170.127444
2,4658149,dsgdb9nsd_000004,2,3,3JHH,4.635745
3,4658150,dsgdb9nsd_000004,3,0,1JHC,164.913304
4,4658151,dsgdb9nsd_000004,3,1,2JHC,14.132798

In [11]:
test[['id', 'scalar_coupling_constant']].to_csv('data/subs/testing_target_normalization_more_features.csv', index=False)